spring:
  application:
    name: pryeureka-registro

server:
  port: 8761

eureka:
  client:
    registry-with-eureka: false
    fetch-registry: false # al conectarnos al servidor evita que jale configuraciones de los otros mictoservicios