server:
  port: 8761 # puerto de acceso

spring:
  application:
    name: weurekaserver # nombre de la aplicación en un entorno Spring para microservicios

eureka:
  client:
    register-with-eureka: false # indica si el cliente de Eureka (en este caso, tu aplicación Spring Boot) debe registrarse en el servidor de Eureka
    fetch-registry: false # indica si al conectarnos al servidor jalara la lista de otros mictoservicios (resolver sus ubicaciones)